### ISSUE TITLE
KEYS command in redis blocks the redis till all the keys are fetched

### ISSUE THREAD

**Issue by asnimansari** [ErickJ3/setui#4]
Instead of KEYS be we should use the SCAN command to fetch the keys matching pattern.

**Comment by ErickJ3** [comment]
@asnimansari 
yep, we can implement SCAN instead of KEYS without much effort! ☺️ this is a "good first issue" for contribution to this project

**Comment by ErickJ3** [comment]
closing the issue, refactor implemented (https://github.com/ErickJ3/setui/pull/5)
